import 'dotenv/config';import mongoose from 'mongoose';import Content from '../models/Content.js';
const hero='https://img.lyfskills.com/additive_phase3_2026-06-04/hero/ChIJ9TkaLWYDYzkRLO7xoJjnarM_l.webp';
const generic=[
'https://images.unsplash.com/photo-1555597673-b21d5c935865?auto=format&fit=crop&w=1200&q=85',
'https://images.unsplash.com/photo-1555597408-26bc8e8e1a3c?auto=format&fit=crop&w=1200&q=85',
'https://images.unsplash.com/photo-1600965962361-9035dbfd1c50?auto=format&fit=crop&w=1200&q=85',
'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=1200&q=85'];
const docs=[
{type:'hero',title:'Train Hard. Stand Strong.',subtitle:'Super Seven Karate Institute',description:'Karate, self-defence, fitness and disciplined training for all ages in Indore.',image:hero,order:0},
{type:'about',title:'Discipline. Confidence. Character.',description:'Super Seven Karate Institute is listed in Indore’s Sanwer Road Industrial Area and is described online as a karate and self-defence training academy for all age groups. Public listings emphasize skilled trainers, discipline, confidence and personal growth.',meta:{address:'394, Premium Paradise, Sanwer Road Industrial Area, Indore, Madhya Pradesh 453111/453555',style:'Karate + Self-defence',languages:'Hindi, English'},order:1},
{type:'program',title:'Karate & Self-Defense',subtitle:'Core verified offering',description:'Traditional karate training with self-defence and fitness emphasis. Open to beginners and experienced students.',image:generic[0],meta:{verified:true},order:1},
{type:'program',title:'Competition Training',subtitle:'Performance pathway',description:'A dedicated competition-focused section can be managed here by the academy. Add confirmed championships and selection pathways through the admin panel.',image:generic[1],meta:{verified:false},order:2},
{type:'program',title:'Fitness & Conditioning',subtitle:'Strength • Mobility • Stamina',description:'Fitness-oriented martial arts conditioning. Confirm exact batch structure with the academy before publishing.',image:generic[2],meta:{verified:false},order:3},
{type:'program',title:'Judo / Taekwondo / MMA / Wushu / Pencak Silat / Ju-Jitsu',subtitle:'Editable program catalogue',description:'Requested programs are available as editable placeholders in this demo. They were not independently verified as current Super Seven offerings during research.',image:generic[3],meta:{verified:false},order:4},
{type:'coach',title:'Divyanshi Pal',subtitle:'Super Seven Sports Academy',description:'Public professional profile identifies Divyanshi Pal with Super Seven Sports Academy and describes her as an international karate player and Pencak Silat Khelo India medalist. Treat detailed qualifications and exact role as subject to academy confirmation.',image:generic[1],meta:{source:'Public LinkedIn profile; verify before publication'},order:1},
{type:'champion',title:'Champions & Students',subtitle:'Student results',description:'Admin-managed student achievement cards. Add verified names, categories, ranks and event results only after academy confirmation.',image:generic[0],meta:{verified:false},order:1},
{type:'achievement',title:'Competitive Martial Arts Track',subtitle:'Academy achievement section',description:'Use this section to publish verified national/international medals, championships and awards. The research found references to competition activity but not enough authoritative evidence to safely invent a complete medal tally.',image:generic[2],meta:{verified:false},order:1},
{type:'branch',title:'Indore — Sanwer Road',subtitle:'Primary listed location',description:'394 Premium Paradise, Sanwer Road Industrial Area, Indore, Madhya Pradesh. Public listings differ on PIN (453111/453555), so confirm the exact postal code with the academy.',meta:{address:'394 Premium Paradise, Sanwer Road Industrial Area, Indore, Madhya Pradesh',map:'https://www.google.com/maps/search/?api=1&query=394%20Premium%20Paradise%20Sanwer%20Road%20Industrial%20Area%20Indore'},order:1},
{type:'schedule',title:'Training Schedule',subtitle:'Mon–Sat listed online',description:'Public listing reports Monday–Saturday classes with varying hours. Another listing shows a broad 6:00 AM–6:30 PM window; exact batch times should be confirmed.',meta:{days:'Monday–Saturday',window:'6:00 AM–6:30 PM',trial:'Trial classes reported available'},order:1},
{type:'fee',title:'₹1,500 / month',subtitle:'Publicly listed training fee',description:'BookMyPlayer currently lists training fees at ₹1,500 per month. Uniform, grading, tournament and other charges are not established by this research.',meta:{amount:1500,currency:'INR'},order:1},
{type:'event',title:'Events & Championships',subtitle:'Admin-managed',description:'Add upcoming camps, belt tests, demonstrations, district/state/national championships and academy events here.',image:generic[0],meta:{verified:false},order:1},
{type:'testimonial',title:'Positive local feedback',subtitle:'Public review summary',description:'Public listings describe experienced/confident trainers, disciplined classes, supportive environment and a focus on self-confidence. One Justdial review published 19 Feb 2026 gave a 5-star rating.',meta:{rating:'5.0 / 5 on Justdial listing; 4.8 / 5 on LyfSkills (87 reviews reported)'},order:1},
{type:'news',title:'Media & Newspaper Coverage',subtitle:'Admin-managed archive',description:'Upload verified newspaper scans, articles, interviews and event coverage from the admin panel. No fabricated press coverage is included in this demo.',order:1},
{type:'affiliation',title:'Affiliations & Recognitions',subtitle:'Verify before publishing',description:'No formal federation accreditation was conclusively established in the research. Use this section for confirmed affiliations, certificates and recognized bodies only.',meta:{verified:false},order:1},
{type:'gallery',title:'Training & Academy Gallery',subtitle:'Replace with academy-owned/licensed media',images:[hero,...generic],meta:{rights:'Confirm image rights before commercial launch'},order:1}
];
await mongoose.connect(process.env.MONGO_URI);await Content.deleteMany({});await Content.insertMany(docs);console.log(`Seeded ${docs.length} content records`);await mongoose.disconnect();
